/*
 Developed by: 
 Eric Mazza

 Date started: 
 06/06/2017

 Description:
 This is an application that I'm creating for my programming culminating, 
 it will allow teachers to log their students, and their information in an easy 
 to manage environment.

 */

import java.io.*;

/**
 *
 * @author ermaz0018
 *
 *
 */
public class CulminatingProject extends javax.swing.JFrame {

    /**
     * Creates new form CulminatingProject
     */
    public CulminatingProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        titleSeperator = new javax.swing.JSeparator();
        loginPanel = new javax.swing.JPanel();
        loginTitle = new javax.swing.JLabel();
        usernamePrompt = new javax.swing.JLabel();
        usernameInput = new javax.swing.JTextField();
        passwordPrompt = new javax.swing.JLabel();
        loginConfirm = new javax.swing.JButton();
        passwordInput = new javax.swing.JPasswordField();
        newAccountPanel = new javax.swing.JPanel();
        newAccountTitle = new javax.swing.JLabel();
        newUsernamePrompt = new javax.swing.JLabel();
        newPasswordPrompt = new javax.swing.JLabel();
        newUsernameInput = new javax.swing.JTextField();
        newPasswordInput = new javax.swing.JPasswordField();
        newAccountConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTitle.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(102, 102, 102));
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitle.setText("Student Haven");

        titleSeperator.setForeground(new java.awt.Color(0, 0, 0));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        loginTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTitle.setText("Log in");

        usernamePrompt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        usernamePrompt.setText("Username:");

        passwordPrompt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        passwordPrompt.setText("Password:");

        loginConfirm.setText("Confirm");
        loginConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernamePrompt)
                    .addComponent(passwordPrompt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(passwordInput))
                .addContainerGap())
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(loginConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginTitle)
                .addGap(28, 28, 28)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamePrompt)
                    .addComponent(usernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordPrompt)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginConfirm)
                .addGap(30, 30, 30))
        );

        newAccountPanel.setBackground(new java.awt.Color(255, 255, 255));

        newAccountTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        newAccountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newAccountTitle.setText("Create an Account");

        newUsernamePrompt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        newUsernamePrompt.setText("Username:");

        newPasswordPrompt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        newPasswordPrompt.setText("Password:");

        newAccountConfirm.setText("Confirm");
        newAccountConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newAccountPanelLayout = new javax.swing.GroupLayout(newAccountPanel);
        newAccountPanel.setLayout(newAccountPanelLayout);
        newAccountPanelLayout.setHorizontalGroup(
            newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newAccountTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(newAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newUsernamePrompt)
                    .addComponent(newPasswordPrompt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newPasswordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(newUsernameInput))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAccountPanelLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(newAccountConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        newAccountPanelLayout.setVerticalGroup(
            newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newAccountTitle)
                .addGap(30, 30, 30)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newUsernamePrompt)
                    .addComponent(newUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(newAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPasswordPrompt)
                    .addComponent(newPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(newAccountConfirm)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(titleSeperator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(newAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginConfirmActionPerformed
        String username;
        String password;

        username = usernameInput.getText();
        password = passwordInput.getText();
        System.out.println("Logging in using these credentials...");
        System.out.println("Username: " + username + "\nPassword: " + password);
        LogIn(username, password);
    }//GEN-LAST:event_loginConfirmActionPerformed

    private void newAccountConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountConfirmActionPerformed
        String username;
        String password;

        username = newUsernameInput.getText();
        password = newPasswordInput.getText();
        System.out.println("Creating a new account... using these credentials: ");
        System.out.println("Username: " + username + "\nPassword: " + password);
        try {
            NewAccount(username, password);
        } catch (IOException e) {
            System.out.println("Didn't allow us to write to the file...");
            System.err.println("Error: " + e);
        }
    }//GEN-LAST:event_newAccountConfirmActionPerformed

    public static void LogIn(String givenUsername, String givenPassword) {
        String path = "Y://Documents/StudentHavenAccounts/" + givenUsername + ".txt";
        File textFile = new File(path);
        FileReader in;
        BufferedReader readFile;
        String realPassword = null;
        givenPassword = "password:" + givenPassword;

        try {
            in = new FileReader(textFile);
            readFile = new BufferedReader(in);
            while ((realPassword = readFile.readLine()) != null) {
                System.out.println(realPassword);
            }
            readFile.close();
            in.close();
        } catch (FileNotFoundException e) {
            System.out.println("No account by that name.");
            System.err.println("FileNotFoundException: " + e.getMessage());
        } catch (IOException e) {
            System.out.println("Problem reading file.");
            System.err.println("IOException: " + e.getMessage());
        }
        if (givenPassword.equals(realPassword)) {
            System.out.println("Logged in!");
        } else {
            System.out.println("The password is incorrect.");
        }
    }

    public static void NewAccount(String username, String password) throws IOException {
        File textFile;
        String path = "Y://Documents/StudentHavenAccounts/" + username + ".txt";
        FileWriter write;
        PrintWriter print_line;
        textFile = new File(path);

        if (textFile.exists()) {
            System.out.println("File already exists.");
        } else {
            try {
                textFile.createNewFile();
                System.out.println("New file created.");
            } catch (IOException e) {
                System.out.println("The file could not be created.");
                System.err.println("IOException: " + e.getMessage());
            }
        }
        write = new FileWriter(path);
        print_line = new PrintWriter(write);
        print_line.printf("%s" + "%n", "password:" + password);
        print_line.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CulminatingProject.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CulminatingProject.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CulminatingProject.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CulminatingProject.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CulminatingProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginConfirm;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton newAccountConfirm;
    private javax.swing.JPanel newAccountPanel;
    private javax.swing.JLabel newAccountTitle;
    private javax.swing.JPasswordField newPasswordInput;
    private javax.swing.JLabel newPasswordPrompt;
    private javax.swing.JTextField newUsernameInput;
    private javax.swing.JLabel newUsernamePrompt;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordPrompt;
    private javax.swing.JSeparator titleSeperator;
    private javax.swing.JTextField usernameInput;
    private javax.swing.JLabel usernamePrompt;
    // End of variables declaration//GEN-END:variables
}
